default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5

development:
  <<: *default
  database: employees_devbootcamp_com_development

test:
  <<: *default
  database: employees_devbootcamp_com_test
